# pipeline.yml (Versión Refactorizada)
stages:
  - name: validate_user_request
    params:
      prompt: "00_agent_request_validator.md"
      model: "gemini-2.0-flash-lite"

  - name: generate_items
    params:
      prompt: "01_agent_dominio.md"
      model: "gemini-2.5-flash"
      temperature: 0.7

  - name: validate_hard

  # - name: validate_facts
  #   params:
  #     prompt: "XX_agent_fact_checker.md"
  #     # Este agente necesita un modelo potente capaz de usar herramientas
  #     model: "gemini-2.0-flash"
  #     # Se asume que el proveedor LLM soporta el uso de herramientas
  #     ## tools: ["Google Search"]

  # - name: polish_item_psychometrics
  #   params:
  #     prompt: "02_agente_maestro_psicometrico.md"
  #     model: "gemini-2.0-flash"
  #     temperature: 0.3

  # - name: refine_item_policy
  #   params:
  #     prompt: "04_agente_maestro_equidad.md"
  #     model: "gemini-2.0-flash-lite"
  #     temperature: 0.5

  - name: validate_soft

  - name: refine_item_style
    params:
      prompt: "05_agente_maestro_estilo.md"
      model: "gemini-2.0-flash"
      temperature: 0.6

  # - name: validate_hard

  # - name: polish_item_psychometrics
  #   params:
  #     prompt: "02_agente_maestro_psicometrico.md"
  #     model: "gemini-2.0-flash"
  #     temperature: 0.3

  - name: finalize_item
    params:
      prompt: "07_agent_final.md"
      model: "gemini-2.0-flash"
      temperature: 0.3

  - name: persist
