# pipeline.yml (Versión Final)
# Define el flujo de ejecución lineal para el sistema SIGIE.

stages:
  # 1. Etapa de creación inicial de ítems
  - name: generate_items
    params:
      prompt: "01_agent_dominio.md"
      # Se pueden añadir aquí params de LLM específicos para esta etapa
      # model: "gpt-4-turbo"

  # 2. Validación programática de reglas duras
  - name: validate_hard

  # 3. Ciclo de validación y refinamiento lógico
  - name: validate_logic
    params:
      prompt: "02_agent_razonamiento.md"
  - name: refine_item_logic
    params:
      prompt: "03_agente_refinador_razonamiento.md"
      # Esta etapa actuará sobre los ítems cuyo estado sea 'validate_logic.fail'
      listen_to_status: "validate_logic.fail"

  # 4. Etapa de corrección de estilo directa
  - name: correct_item_style
    params:
      prompt: "04_agente_refinador_estilo.md"

  # 5. Ciclo de validación y refinamiento de políticas
  - name: validate_policy
    params:
      prompt: "05_agent_politicas.md"
  - name: refine_item_policy
    params:
      prompt: "06_agente_refinador_politicas.md"
      listen_to_status: "validate_policy.fail"

  # 6. Validación programática de reglas suaves (advertencias)
  - name: validate_soft

  # 7. Etapa de evaluación final por un LLM
  - name: finalize_item
    params:
      prompt: "07_agent_final.md"
      # model: "gpt-4" # Podríamos usar un modelo más potente para el juicio final

  # 8. Persistencia final en la base de datos
  - name: persist
