# pipeline.yml
# Define el flujo de ejecución lineal para el sistema SIGIE.
# Las etapas se ejecutan en el orden listado.

stages:
  # 1. Etapa de creación inicial de ítems
  - name: generate_items
    params:
      prompt: "01_agent_dominio.md"
      provider: gemini
      model: "gemini-2.0-flash"
      temperature: 0.7
      max_tokens: 4096

  # 2. Validación programática de reglas duras
  - name: validate_hard

  # 3. Ciclo de validación y refinamiento lógico
  - name: validate_item_logic
    params:
      prompt: "02_agent_razonamiento.md"
      provider: gemini
      model: gemini-2.0-flash
      temperature: 0.3
      max_tokens: 2048

  - name: refine_item_logic
    listen_to_status_pattern: "logic_validation.needs_revision"
    params:
      prompt: "03_agente_refinador_razonamiento.md"
      provider: gemini
      model: gemini-2.0-flash
      temperature: 0.5
      max_tokens: 4096

  # 4. Ciclo de validación y refinamiento de contenido
  - name: validate_content_validity
    params:
      prompt: "XX_agent_content_validity.md"
      provider: gemini
      model: gemini-2.0-flash
      temperature: 0.3
      max_tokens: 2048

  - name: refine_item_content
    listen_to_status_pattern: "content_validation.needs_revision"
    params:
      prompt: "03B_agente_refinador_contenido.md"
      provider: gemini
      model: gemini-2.0-flash
      temperature: 0.5
      max_tokens: 4096

  # 5. Ciclo de validación y refinamiento de políticas
  - name: validate_policy
    params:
      prompt: "05_agent_politicas.md"
      provider: gemini
      model: gemini-2.0-flash
      temperature: 0.3
      max_tokens: 2048

  - name: refine_item_policy
    listen_to_status_pattern: "policy_validation.needs_revision"
    params:
      prompt: "06_agente_refinador_politicas.md"
      provider: gemini
      model: gemini-2.0-flash
      temperature: 0.5
      max_tokens: 4096

  # 6. Validación programática de reglas suaves (advertencias)
  - name: validate_soft

  # 7. Etapa de corrección de estilo directa
  - name: refine_item_style
    params:
      prompt: "04_agente_refinador_estilo.md"
      provider: gemini
      model: "gemini-2.0-flash"
      temperature: 0.6
      # --- CORRECCIÓN ---
      # Aumentamos el límite para evitar que la respuesta JSON se corte.
      max_tokens: 8192

  # 8. Etapa de evaluación final por un LLM
  - name: finalize_item
    params:
      prompt: "07_agent_final.md"
      provider: gemini
      model: "gemini-2.0-flash"
      temperature: 0.2
      max_tokens: 2048

  # 9. Persistencia final en la base de datos
  - name: persist
