[theme]
# El color principal para los elementos interactivos (botones, sliders, etc.)
primaryColor = "#0068c9"

# El color de fondo principal de la aplicación
backgroundColor = "#f0f2f6"

# El color de fondo para elementos como la barra lateral y los contenedores
secondaryBackgroundColor = "#e8eaf1"

# El color del texto principal
textColor = "#262730"

# La fuente a utilizar. "sans serif" es una opción limpia y legible.
font = "sans serif"
